export const TAMIL_NADU_DISTRICTS = [
  { id: "ariyalur", name: "Ariyalur", tamilName: "அரியலூர்" },
  { id: "chengalpattu", name: "Chengalpattu", tamilName: "செங்கல்பட்டு" },
  { id: "chennai", name: "Chennai", tamilName: "சென்னை" },
  { id: "coimbatore", name: "Coimbatore", tamilName: "கோவை" },
  { id: "cuddalore", name: "Cuddalore", tamilName: "கடலூர்" },
  { id: "dharmapuri", name: "Dharmapuri", tamilName: "தர்மபுரி" },
  { id: "dindigul", name: "Dindigul", tamilName: "திண்டுக்கல்" },
  { id: "erode", name: "Erode", tamilName: "ஈரோடு" },
  { id: "kallakurichi", name: "Kallakurichi", tamilName: "கள்ளக்குறிச்சி" },
  { id: "kanchipuram", name: "Kanchipuram", tamilName: "காஞ்சிபுரம்" },
  { id: "kanyakumari", name: "Kanyakumari", tamilName: "கன்னியாகுமரி" },
  { id: "karur", name: "Karur", tamilName: "கரூர்" },
  { id: "krishnagiri", name: "Krishnagiri", tamilName: "கிருஷ்ணகிரி" },
  { id: "madurai", name: "Madurai", tamilName: "மதுரை" },
  { id: "mayiladuthurai", name: "Mayiladuthurai", tamilName: "மயிலாடுதுறை" },
  { id: "nagapattinam", name: "Nagapattinam", tamilName: "நாகப்பட்டிணம்" },
  { id: "namakkal", name: "Namakkal", tamilName: "நாமக்கல்" },
  { id: "nilgiris", name: "Nilgiris", tamilName: "நீலகிரி" },
  { id: "perambalur", name: "Perambalur", tamilName: "பெரம்பலூர்" },
  { id: "pudukkottai", name: "Pudukkottai", tamilName: "புதுக்கோட்டை" },
  { id: "ramanathapuram", name: "Ramanathapuram", tamilName: "ராமநாதபுரம்" },
  { id: "ranipet", name: "Ranipet", tamilName: "ராணிப்பேட்டை" },
  { id: "salem", name: "Salem", tamilName: "சேலம்" },
  { id: "sivaganga", name: "Sivaganga", tamilName: "சிவகங்கை" },
  { id: "tenkasi", name: "Tenkasi", tamilName: "தென்காசி" },
  { id: "thanjavur", name: "Thanjavur", tamilName: "தஞ்சாவூர்" },
  { id: "theni", name: "Theni", tamilName: "தேனி" },
  { id: "thoothukudi", name: "Thoothukudi", tamilName: "தூத்துக்குடி" },
  { id: "tiruchirappalli", name: "Tiruchirappalli", tamilName: "திருச்சிராப்பள்ளி" },
  { id: "tirunelveli", name: "Tirunelveli", tamilName: "திருநெல்வேலி" },
  { id: "tirupathur", name: "Tirupathur", tamilName: "திருப்பத்தூர்" },
  { id: "tiruppur", name: "Tiruppur", tamilName: "திருப்பூர்" },
  { id: "tiruvallur", name: "Tiruvallur", tamilName: "திருவள்ளூர்" },
  { id: "tiruvannamalai", name: "Tiruvannamalai", tamilName: "திருவண்ணாமலை" },
  { id: "tiruvarur", name: "Tiruvarur", tamilName: "திருவாரூர்" },
  { id: "vellore", name: "Vellore", tamilName: "வேலூர்" },
  { id: "viluppuram", name: "Viluppuram", tamilName: "விழுப்புரம்" },
  { id: "virudhunagar", name: "Virudhunagar", tamilName: "விருதுநகர்" },
];

export const SERVICE_CATEGORIES = [
  { id: "plumber", name: "Plumber", tamilName: "குழாய் பொருத்துபவர்", icon: "fas fa-wrench" },
  { id: "electrician", name: "Electrician", tamilName: "மின்சார தொழிலாளி", icon: "fas fa-bolt" },
  { id: "painter", name: "Painter", tamilName: "ஓவியர்", icon: "fas fa-paint-roller" },
  { id: "mechanic", name: "Mechanic", tamilName: "இயந்திர வல்லுநர்", icon: "fas fa-tools" },
  { id: "septic_cleaner", name: "Septic Cleaner", tamilName: "கழிவுநீர் சுத்தம் செய்பவர்", icon: "fas fa-recycle" },
  { id: "carpenter", name: "Carpenter", tamilName: "தச்சர்", icon: "fas fa-hammer" },
  { id: "mason", name: "Mason", tamilName: "கொத்தனார்", icon: "fas fa-brick-wall" },
  { id: "gardener", name: "Gardener", tamilName: "தோட்டக்காரர்", icon: "fas fa-seedling" },
  { id: "cleaner", name: "House Cleaner", tamilName: "வீட்டு சுத்தம் செய்பவர்", icon: "fas fa-broom" },
  { id: "appliance_repair", name: "Appliance Repair", tamilName: "உபகரண பழுது நீக்கல்", icon: "fas fa-screwdriver" },
];

export const SUPER_ADMIN_PHONES = ["9000000001", "9000000002"];
